spring:
  security:
    oauth2:
      jwt:
        signingKey: 123456
      expire:
        seconds: 7200 
  
gate: 
  ignore: 
    authentication: 
     startWith: /oauth,/open
     
 #自定义权限配置
tiger:
  auth:
     browser:
      loginPage: /login.html # 这里可以配置成自己的非标准登录界面
      loginType: JSON